import type { Metadata } from 'next'
import { Button } from '@/components/ui/button'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Mendelu webshop | Home',
  description: 'Generated by create next app'
}

export default async function HomePage() {
  return (
    <div className="max-w-sm min-w-full mx-auto">
      <h1 className="text-4xl mb-4">Welcome to the best webshop ever</h1>
      <Button asChild>
        <Link href="/products">Go to shop</Link>
      </Button>
    </div>
  )
}
