import Product from '@/components/product'
import type { Metadata } from 'next'
// You can replace this mock data with data from an api
import { PRODUCTS_MOCK_DATA } from '@/constants/products'
// import type { ProductsResponse } from '@/types/products'

export const metadata: Metadata = {
  title: 'Mendelu webshop | Products',
  description: 'Generated by create next app'
}

export default async function ProductsPage() {
  // const res = await fetch('http://localhost:3000/api/products')
  // const data: ProductsResponse = await res.json()

  return (
    <div className="max-w-sm min-w-full gap-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
      {PRODUCTS_MOCK_DATA.map((product) => (
        <Product key={product.id} product={product} />
      ))}
    </div>
  )
}
